version: 0.2.{build}

os: Visual Studio 2015

platform: Any CPU

configuration: Release

build:
  verbosity: minimal
  publish_nuget: true
  publish_nuget_symbols: true
  project: src/EPiDependentSelection.sln

cache:
  - packages -> **\packages.config

environment:
  COVERALLS_REPO_TOKEN:
    secure: Gi2xlqI4/SNhWzFAJ5d5BE3hKV4gzEvK9mRWqgzaXDn6aZUmQ3ZmOv6nSwfAqgb3

before_build:
  - cmd: nuget restore src/EPiDependentSelection.sln -verbosity quiet

after_test:
  - src\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[EPiDependentSelection]*" -target:"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\MSTest.exe" -targetargs:"/testcontainer:Src/EPiDependentSelection.Test/bin/release/EPiDependentSelection.Test.dll" -output:coverage.xml
  - src\packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml